version: '3'
services:
  transaction-api:
    container_name: transaction-api
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/var/www
    ports:
      - 9650:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: transaction-mysql
    volumes:
      - ./transaction-mysql-data:/var/lib/mysql
    ports:
      - 3360:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transaction_database
      MYSQL_TCP_PORT: 3306
networks:
  transaction-api-network:
    driver: bridge